### ISSUE TITLE
FEATURE - Show list of guides shortlisted for each dev type in SAP Business Application Studio 

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#245] opened 2022-09-22 19:48 UTC
_As a **developer using Guided Development in any of the dev space in SAP Business Application Studio**,
I want to see a relevant list of shortlisted guides by default which is based on the software componenets per dev space type ,
so that I can be shown only a subset of relevant guides which is of potential interest to me rather than seeing ALL the 1k guides_

### Description

- This will be the one of the first step to make the guide list smarter. While using specific dev space in SBAS, user really don't need access to hundreds of unrelated guide. 
- With each dev space, we can create a sort of `dev space<->product/component mapping` which will help in shortlisting 1st wave.
- For `SAP Fiori` dev space, these are the software components which needs to be shortlisted (List needs to finalized): 
`CA-UX-IDE`
`CA-FE-FLP-EU`
`CA-FE-FLP-DT`
`CA-FE-FAL`
`CA-UI2-INT-BE`
`CA-UI2-INT-FE`
`CA-UI2-THD`

### Technical Design
To be added by @Klaus-Keller 

### UI Changes
- As part of this US, we want to make minimum UI changes as later there will be more dedicated UI work once we start working on `Guided Answers Home Page`
- When the Guide List is shortlisted based on filtering done due to software components, when GA is opened, it should show the active filters like this:
 
![image](https://user-images.githubusercontent.com/59027566/192880770-67e17cc1-fec1-49a3-b0a6-838401b95189.png)

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a dev space of type `SAP Fiori` open in SBAS
**when** I open Guided Answers
**then** the list shown to me should be relevant to `SAP Fiori` topic representing from shortlisted components

### Tasks
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by carwelsh** [comment] 2022-09-22 21:05
@theStiggySpd - I think this is a duplicate of this issue https://github.com/SAP/guided-answers-extension/issues/232

Please review it as it contains Goran's suggestions then we can close it and keep this issue.

**Comment by theStiggySpd** [comment] 2022-09-28 20:29
> @theStiggySpd - I think this is a duplicate of this issue #232
> 
> Please review it as it contains Goran's suggestions then we can close it and keep this issue.

Hello @carwelsh This ticket will be a subset. We can keep https://github.com/SAP/guided-answers-extension/issues/232 an en epic and plan the overall smart features there

**Closed** 2022-11-01 14:58 UTC
Labels: type:feature, guided-answers-extension
