### ISSUE TITLE
BUG - Screen jump - do not prevent overflow when dialogs are open

### ISSUE THREAD

**Issue by gpeuc** [SAP/guided-answers-extension#338] opened 2022-12-13 12:50 UTC
At the moment this is happening when dialogs open/close:

![screen jump](https://user-images.githubusercontent.com/44162846/207322209-0a287a21-8c46-463d-9b34-d3e075ebab52.gif)

You can see that even the wizard step is jumping because the screen size changes.

This happens because we hide/show the scrollbar. Due to this scrollbar manipulation screen gains/loses pixel size as scrollbar takes up about 10px of space.

And in the case of sending feedback, because there are two consecutive popups, the screen just dances all the time.

We need to remove this class from `body` when dialogs are open.

<img width="305" alt="Screenshot 2022-12-13 at 12 50 13" src="https://user-images.githubusercontent.com/44162846/207322655-90a2730b-13fe-4b4f-b6a5-7df1d27b8087.png">

- - - -
@sanat-thukral

**Comment by sanat-thukral** [comment] 2022-12-13 14:22
Thanks Goran, will pick this up

**Comment by carwelsh** [comment] 2023-01-25 12:15
Hi Sanat, has this been merged?  Can I test it or has Goran reviewed it?

**Comment by sanat-thukral** [comment] 2023-01-25 23:50
Hi Caroline, I haven't gotten to this bug yet. I'm finishing up some changes on this [PR](https://github.com/SAP/guided-answers-extension/pull/335) which contains a lot of other fixes. Hoping to first finish those off and then pick this one up.

**Comment by hitesh-parmar** [comment] 2024-03-19 13:17
Hi @gpeuc, This looks similar to the bug you mentioned here https://github.com/SAP/guided-answers-extension/issues/330 
This is solved with [PR](https://github.com/SAP/guided-answers-extension/pull/335)

I think we could close this bug. Could you please retest once?

**Comment by gpeuc** [comment] 2024-03-19 14:03
@hitesh-parmar Hm but I don't see it as fixed (I've just installed latest from Dev). The elements on screen still move left/right due to the fact we hide the scrollbar when the dialog opens. When the scrollbar is gone, there's extra 20 pixels of space available, and the content rearranges itself to utilise that space. You can see it in the mini-toolbar itself, look, I will isolate just the toolbar in the screengrab as I click the dialog and then close it:

![2024-03-19 14 02 21](https://github.com/SAP/guided-answers-extension/assets/44162846/b69c3ea0-fc2c-4f74-85fb-97f7cee3ecff)

This happens with entire content column, since it suddenly gains 20px space.

**Comment by hitesh-parmar** [comment] 2024-03-19 14:49
Thanks for checking @gpeuc . Not sure why I wasn't able to reproduce the issue earlier. I just resized my window and could reproduce the issue now.

**Comment by gpeuc** [comment] 2024-03-19 19:16
@hitesh-parmar You need to have content long enough so it causes scrollbar to appear. Won't work with small content nodes that fit entirely onto one screen.

**Comment by hitesh-parmar** [comment] 2024-06-13 14:26
@gpeuc Could you please retest and close this bug? Solved with PR #601

**Comment by hitesh-parmar** [comment] 2024-06-13 14:56
> @hitesh-parmar You need to have content long enough so it causes scrollbar to appear. Won't work with small content nodes that fit entirely onto one screen.

From my side, I still cannot reproduce it even without the fix 😅

**Comment by gpeuc** [comment] 2024-06-17 09:43
@hitesh-parmar Yeah, I cannot get it to blitz again, so there had to be some CSS trickery implemented there.

**Comment by hitesh-parmar** [comment] 2024-06-18 06:55
Thanks for checking @gpeuc . Let me close this issue now.

**Closed by hitesh-parmar** 2024-06-18 06:55 UTC
Labels: type:bug, guided-answers-extension
